	
	<div id="footer">
		<div class="wrapper">
		<p class="copyright">&copy; Copyright <$date format="yyyy"/$>, <$websitename/$>. All Rights Reserved.</p>

		<$globalmenu cssClass="footerNav left" showLevels="1" alwaysShowChildren="false" showHome="true"/$>


		<p class="right">Designed and Developed by <a href="http://diosdesign.com" target="_blank">Dios Design</a></p>

			<br class="clear" />
		</div><!--//wrapper-->
	</div><!--//footer-->
	
</div>


</div>

		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="js/jquery-1.9.0.min.js"><\/script>')</script>
        <script src="js/main.js"></script>


</body>
</html>